version: "3.8"

services:
  api:
    build: ./api
    container_name: sentiment-api
    ports:
      - "8000:8000"
    volumes:
      - ./model:/app/model
    restart: unless-stopped

  mlflow:
    build: ./mlflow_server
    container_name: mlflow-server
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow_data:/mlflow_artifacts
