name: CD-PROD

on:
  push:
    branches:
      - main

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to PROD server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.MLOPS_HOST }}
          username: ${{ secrets.MLOPS_USER }}
          key: ${{ secrets.MLOPS_SSH_KEY }}
          script: |
            cd ${{ secrets.MLOPS_PROJECT_DIR }}
            git fetch --all
            git checkout main
            git pull origin main
            docker-compose down
            docker-compose up -d --build
            docker system prune -f
